main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.GoodsListView.as_view(), name='goods'),
    path('<slug:slug>/', views.GoodsDetailView.as_view(), name='goods-detail'),
    path('category/<slug:slug>/', views.GoodsListByCategoryView.as_view(),
         name='goods-by-category'),
]

mysite/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.contrib.flatpages.views import flatpage
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from main.views import index

urlpatterns = [
    path('', index, name='homepage'),
    path('admin/', admin.site.urls),
    path('about/', flatpage, {'url': '/about/'}, name='about'),
    path('contact/', flatpage, {'url': '/contact/'}, name='contact'),
    path('goods/', include('main.urls')),

    path('logout/', LogoutView.as_view(next_page='homepage'), name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.urls import reverse
from uuslug import uuslug


class Goods(models.Model):
    name = models.CharField('Название', max_length=100)
    description = models.TextField('Описание', blank=True)
    image = models.ImageField('Изображение', upload_to='goods', blank=True)
    price = models.DecimalField('Цена', max_digits=12, decimal_places=2)
    quantity = models.IntegerField('Количество', default=1)
    category = models.ForeignKey('GoodsCategory', on_delete=models.CASCADE,
                                 verbose_name='Категория')
    seller = models.ForeignKey('Seller', on_delete=models.CASCADE, related_name="goods",
                               verbose_name='Продавец')
    tags = models.ManyToManyField('GoodsTag', related_name="goods",
                                  verbose_name='Тэги')
    draft = models.BooleanField('Черновик', default=False)

    slug = models.SlugField(max_length=200, editable=False)
    article = models.CharField('Артикул', max_length=10, editable=False)

    def save(self, *args, **kwargs):
        self.article = str(self.id).zfill(6)
        self.slug = uuslug(self.name, instance=self)
        super().save(*args, **kwargs)

    class Meta:
        ordering = ['draft', 'name', 'price']
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('goods-detail', args=[self.slug])

    @property
    def stock_status(self):
        return 'в наличии' if self.quantity > 0 else 'нет в наличии'


class GoodsCategory(models.Model):
    name = models.CharField('Название', max_length=30, unique=True)
    slug = models.SlugField('Ссылка', max_length=200, unique=True)
    image = models.ImageField('Изображение', upload_to='categories', blank=True)
    draft = models.BooleanField('Черновик', default=False)

    class Meta:
        ordering = ['draft', 'name']
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('goods-by-category', args=[self.slug])


class GoodsTag(models.Model):
    name = models.CharField('Название', max_length=120, unique=True)
    slug = models.SlugField(max_length=200, editable=False)

    class Meta:
        ordering = ['name']
        verbose_name = 'Тэг'
        verbose_name_plural = 'Тэги'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = uuslug(self.name, instance=self)
        super().save(*args, **kwargs)


class Seller(models.Model):
    first_name = models.CharField('Имя', max_length=100)
    last_name = models.CharField('Фамилия', max_length=100)
    birth_date = models.DateField('Дата рождения', blank=True, null=True)
    email = models.EmailField('E-mail', max_length=100)

    @property
    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    class Meta:
        ordering = ['first_name', 'last_name']
        verbose_name = 'Продавец'
        verbose_name_plural = 'Продавцы'

    def __str__(self):
        return self.full_name

main/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView

from main.models import Goods, GoodsCategory


def index(request):
    template_name = 'main/index.html'
    context = {'turn_on_block': True}
    return HttpResponse(render(request, template_name, context=context))


class GoodsListView(ListView):
    model = Goods
    template_name = 'main/goods_grid.html'
    paginate_by = 2

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Все товары'
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        tag_slug = self.request.GET.get('tag')
        if tag_slug:
            queryset = queryset.filter(tags__slug=tag_slug)
        return queryset


class GoodsListByCategoryView(ListView):
    model = Goods
    template_name = 'main/goods_grid.html'
    paginate_by = 2

    def get_queryset(self):
        self.category = get_object_or_404(GoodsCategory, slug=self.kwargs['slug'])
        queryset = Goods.objects.filter(category=self.category)

        tag_slug = self.request.GET.get('tag')
        if tag_slug:
            queryset = queryset.filter(tags__slug=tag_slug)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Категория: {self.category}'
        return context


class GoodsDetailView(DetailView):
    model = Goods
    template_name = 'main/goods_detail.html'

    def get_object(self, **kwargs):
        self.goods = get_object_or_404(Goods, slug=self.kwargs['slug'])
        return self.goods

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Категория: {self.goods.category}'
        return context

main/templates/main/goods_card.html
<div class="card-body">
  <img src="{{ goods.image.url }}" class="card-img-top mb-2" width="100%"
       height="180px" alt="...">
  <h5 class="card-title">{{ goods.price }} ₽</h5>
  <p class="card-text"><a href="{{ goods.get_absolute_url }}" class="text-dark">{{ goods.name }}</a></p>
  <a href="#" class="btn btn-warning">В корзину</a>
</div>

main/templates/main/goods_detail.html
{% extends "base.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}

<div class="card mb-3">
  <div class="row g-0">
    <div class="col-md-6">
      <div class="card-body d-flex justify-content-center align-items-center">
      <img src="{{ goods.image.url }}" style="width: 100%; max-height: 300px" alt="{{ goods.title }}">
      </div>
    </div>
    <div class="col-md-6">
      <div class="card-body">
        <h2 class="card-title">{{ goods.name }}</h2>
        <span class="card-text text-muted">Продавец: {{ goods.seller.full_name }}</span>
        <h3 class="pt-3 pb-3"><span class="fw-bolder badge bg-secondary rounded-pill fs-30">{{ goods.price }} ₽</span></h3>

        <p class="card-text">{{ goods.description|truncatechars:500 }}</p>
        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
      </div>
      <div class="d-grid gap-2">
        <button class="btn btn-warning" type="button">Добавить в корзину</button>
      </div>
    </div>
  </div>
  <div class="row g-0 pt-4">
    <div class="card-body">

      <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item" role="presentation">
          <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#description" type="button" role="tab" aria-controls="home" aria-selected="true">
            <span class="card-title h3">Описание</span>
          </button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#specifications" type="button" role="tab" aria-controls="profile" aria-selected="false">
            <span class="card-title h3">Характеристики</span>
          </button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="contact-tab" data-bs-toggle="tab" data-bs-target="#reviews" type="button" role="tab" aria-controls="contact" aria-selected="false">
            <span class="card-title h3">Отзывы</span>
          </button>
        </li>
      </ul>
      <div class="tab-content" id="myTabContent">
        <div class="p-3 tab-pane fade show active" id="description" role="tabpanel" aria-labelledby="home-tab"><p class="card-text text-muted">{{ goods.description }}</p></div>
        <div class="p-3 tab-pane fade" id="specifications" role="tabpanel" aria-labelledby="profile-tab"><p class="card-text text-muted">
          Характеристики отсутствуют для данного товара</p></div>
        <div class="p-3 tab-pane fade" id="reviews" role="tabpanel" aria-labelledby="contact-tab"><p class="card-text text-muted">Нет отзывов</p></div>
      </div>


    </div>
  </div>
</div>

{% endblock %}

main/templates/main/goods_grid.html
{% extends "base.html" %}
{% load custom_tags %}

{% block head-extend %}{% endblock %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
  <div class="row row-cols-3 g-4">
    {% if goods_list %}
      {% for goods in goods_list %}
        <div class="col">
          <div class="card">
            {% include 'main/goods_card.html' with goods=goods %}
          </div>
        </div>
      {% endfor %}
    {% else %}
      <p>По Вашему запросу товаров не найдено</p>
    {% endif %}
  </div>

  {% include 'main/snippets/goods_pagination.html' %}

{% endblock %}

{% block sidebar %}
<div class="col-3 border rounded ">
  <div class="row">
    <div class="card-body">
      <span class="h4">Тэги</span>
      {% goods_tags_buttons %}
    </div>
  </div>


  <div class="row">
    <div class="card-body">
      <span class="h4">Бренды</span>
      <div id="brands">
          <div class="checkbox"><label><input type="checkbox" name="brands[]" value="1"> Apple</label></div>
          <div class="checkbox"><label><input type="checkbox" name="brands[]" value="2"> Samsung</label></div>
          <div class="checkbox"><label><input type="checkbox" name="brands[]" value="3"> Lenovo</label></div>
          <div class="checkbox"><label><input type="checkbox" name="brands[]" value="4"> Что-то еще</label></div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="card-body">
      <span class="h4">Фильтр по ценам</span>
      <div id="prices-label">5000 - 50000 руб.</div>
      <input type="hidden" id="min-price" name="min_price" value="5000">
      <input type="hidden" id="max-price" name="max_price" value="50000">
      <div id="prices"></div>
    </div>
  </div>
  <div class="row">
    <div class="card-body">
      <span class="h4">Сортировка</span>
      <br>
      <select id="sort" name="sort" class="form-control">
          <option value="price_asc">По цене, сначала дешевые</option>
          <option value="price_desc">По цене, сначала дорогие</option>
          <option value="good_asc">По названию, A-Z</option>
          <option value="good_desc">По названию, Z-A</option>
      </select>
    </div>
  </div>

</div>

{% endblock %}

main/templates/main/index.html
{% extends "base.html" %}
{% load custom_tags %}
{% load flatpages %}

{% block content %}
  {% get_flatpages as flatpages %}
  Текущее время: {% current_time %}

  {% if turn_on_block %}
    <div>
      <b>Передан параметр turn_on_block</b>
    </div>
  {% endif %}
  <ul>
    {% for page in flatpages %}
      <li><a href="{{ page.url }}">{{ page.title }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

main/templates/main/snippets/goods_categories_links.html
{% for category in categories %}
  <a class="{{ html_class }}" href="{{ category.get_absolute_url }}">{{ category.name|capfirst }}</a>
{% endfor %}

main/templates/main/snippets/goods_pagination.html
{% load custom_tags %}

<div class="mt-4">

    {% if page_obj.paginator.num_pages > 1 %}
    <div class="border rounded card-body d-flex justify-content-between align-items-center">
      <span>
        Показано {{ page_obj.start_index }}-{{ page_obj.end_index }} из {{ page_obj.paginator.count }} товаров
      </span>


      <nav aria-label="Page navigation">
        <ul class="pagination" style="margin-bottom: 0 !important;">
          {% if page_obj.has_previous %}
            <li class="page-item">
              <a class="page-link" href="{% add_get_params_to_url request.build_absolute_uri page=page_obj.previous_page_number%}">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>
            <li class="page-item">
              <a class="page-link" href="{% add_get_params_to_url request.build_absolute_uri page=page_obj.previous_page_number%}">
                {{ page_obj.previous_page_number }}
              </a>
            </li>
          {% endif %}
          <li class="page-item active">
            <a class="page-link" href="{% add_get_params_to_url request.build_absolute_uri page=page_obj.number%}">
              {{ page_obj.number }}
            </a>
          </li>
          {% if page_obj.has_next %}
            <li class="page-item">
              <a class="page-link" href="{% add_get_params_to_url request.build_absolute_uri page=page_obj.next_page_number %}">
                {{ page_obj.next_page_number }}
              </a>
            </li>
            <li class="page-item">
              <a class="page-link" href="{% add_get_params_to_url request.build_absolute_uri page=page_obj.next_page_number %}">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
          {% endif %}
        </ul>
      </nav>

      </div>
    {% endif %}
</div>

main/templates/main/snippets/goods_tags_buttons.html
<div class="goods-tags">
  {% for tag in tags %}
    {% if request.GET.tag == tag.slug %}
    <a type="button" class="btn btn-primary btn-sm mb-1" href="?tag={{ tag.slug }}">{{ tag.name }}</a>
    {% else %}
    <a type="button" class="btn btn-secondary btn-sm mb-1" href="?tag={{ tag.slug }}">{{ tag.name }}</a>
    {% endif %}
  {% endfor %}
</div>

main/templates/main/snippets/pagination.html
{% load custom_tags %}

<div class="mt-4">

    {% if page_obj.paginator.num_pages > 1 %}
    <div class="border rounded card-body d-flex justify-content-between align-items-center">
      <span>
        Показано {{ page_obj.start_index }}-{{ page_obj.end_index }} из {{ page_obj.paginator.count }} товаров
      </span>


      <nav aria-label="Page navigation">
        <ul class="pagination" style="margin-bottom: 0 !important;">
          {% if page_obj.has_previous %}
            <li class="page-item">
              <a class="page-link" href="{% set_get_params request.build_absolute_uri page=page_obj.previous_page_number%}">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>
            <li class="page-item">
              <a class="page-link" href="{% set_get_params request.build_absolute_uri page=page_obj.previous_page_number%}">
                {{ page_obj.previous_page_number }}
              </a>
            </li>
          {% endif %}
          <li class="page-item active">
            <a class="page-link" href="{% set_get_params request.build_absolute_uri page=page_obj.number%}">
              {{ page_obj.number }}
            </a>
          </li>
          {% if page_obj.has_next %}
            <li class="page-item">
              <a class="page-link" href="{% set_get_params request.build_absolute_uri page=page_obj.next_page_number %}">
                {{ page_obj.next_page_number }}
              </a>
            </li>
            <li class="page-item">
              <a class="page-link" href="{% set_get_params request.build_absolute_uri page=page_obj.next_page_number %}">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
          {% endif %}
        </ul>
      </nav>

      </div>
    {% endif %}
</div>

main/templates/main/snippets/tags_cloud.html
<div class="goods-tags">
  {% for tag in tags %}
    {% if request.GET.tag == tag.slug %}
    <a type="button" class="btn btn-primary btn-sm mb-1" href="?tag={{ tag.slug }}">{{ tag.name }}</a>
    {% else %}
    <a type="button" class="btn btn-secondary btn-sm mb-1" href="?tag={{ tag.slug }}">{{ tag.name }}</a>
    {% endif %}
  {% endfor %}
</div>

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"
        rel="stylesheet">
  <link href="{% static "css/main_styles.css" %}"
        rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css">

  {% block head-extend %}{% endblock %}

  <title>{% block title %}E-commerce{% endblock %}</title>

  <!-- Custom styles for this template -->
</head>

<body>
{% include 'base_header.html' %}

<main role="main">
  <div class="container mt-4 mb-5">
    <div class="row">
      <div class="col">
        {% block content %}
          <b>Здесь пока ничего нет</b>
        {% endblock %}
      </div>

      {% block sidebar %}
      {% endblock %}

    </div>
  </div>

</main>

{% include 'base_footer.html' %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</body>

</html>

templates/base_footer.html
<footer class="p-3" style="background: #efefef">
  <div class="container mt-4">
      <div class="row">
        <div class="col">
          <p>Онлайн-магазин E-commerce</p>
        </div>
        <div class="col">
          <div class="d-flex justify-content-end">
            <i class="fab fa-facebook-f"></i>
            <i class="fab fa-twitter"></i>
            <i class="fab fa-youtube"></i>
            <i class="fab fa-google-plus-g"></i>
            <i class="fab fa-instagram"></i>
          </div>
        </div>
      </div>
  </div>
</footer>

templates/base_header.html
{% load custom_tags %}
{% load static %}
<header>
<div class="p-3 border-bottom">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none ah_check_tooltip">
        <object type="image/svg+xml" data="{% static 'img/logo.svg' %}" class="bi me-2" width="34" height="40"></object>
      </a>

      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href="{% url 'homepage' %}" class="nav-link px-2">Главная</a></li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Магазин</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'goods' %}">Все товары</a>
            <hr class="dropdown-divider">
            {% goods_categories_links %}
          </div>
        </li>
        <li><a href="{% url 'about' %}" class="nav-link px-2">О нас</a></li>
        <li><a href="{% url 'contact' %}" class="nav-link px-2">Контакты</a></li>
      </ul>

      <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
        <input type="search" class="form-control" placeholder="Search...">
      </form>


      {% if user.is_authenticated %}

        <div class="dropdown text-end">
          <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle ah_check_tooltip" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle">
            {{ user }}
          </a>
          <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1" style="">
            <li><a class="dropdown-item ah_check_tooltip" href="#">New project...</a></li>
            <li><a class="dropdown-item ah_check_tooltip" href="#">Settings</a></li>
            <li><a class="dropdown-item ah_check_tooltip" href="#">Profile</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item ah_check_tooltip" href="{% url 'logout' %}">Sign out</a></li>
          </ul>
      </div>
      {% else %}
        <button type="button" class="btn btn-outline-primary me-2">Login</button>
        <button type="button" class="btn btn-primary">Sign-up</button>
      {% endif %}
    </div>
  </div>
</div>
{% url 'homepage' as home %}
{% if request.get_full_path != home %}
<div class="p-3" style="background: #efefef">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-start">
      <span class="fw-normal align-middle">Home > Single Page</span>
    </div>
  </div>
</div>
{% endif %}
</header>